# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "My awesome app"
  lane :android_firebase do
    gradle(task: "assembleRelease")
    firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        service_credentials_file: ENV["FIREBASE_LOGIN_CREDENTIALS"],
        release_notes: "Automated deployment from Fastlane",
        android_artifact_path: ENV["ARTIFACT_PATH"],
        groups_file: ENV["GROUPS_FILE"]
    )
  end
end
